apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kubeflows.operators.ibm.com
spec:
  group: operators.ibm.com
  names:
    kind: Kubeflow
    listKind: KubeflowList
    plural: kubeflows
    singular: kubeflow
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
